source = ~/.config/hyprlock/colors.conf

general {
    disable_loading_bar = true
    hide_cursor = true
}

background {
    monitor =
    color = $background
    blur_passes = 2
    blur_size = 4
}

input-field {
    monitor =
    size = 250, 50
    outline_thickness = 2
    dots_center = true
    outer_color = $accent
    inner_color = $backgroundAlt
    font_color = $foreground
    placeholder_text = <span foreground="##8B8B93">Password...</span>
    shadow_passes = 0
    position = 0, -20
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%H:%M")"
    color = $foreground
    font_size = 64
    position = 0, 150
    halign = center
    valign = center
}
